adding 2024 folder, removing redundant cfp page and updating organizers
mlforsystems/mlforsystems.github.io pull request #8
Opened 2024-08-19 17:54 UTC by pmusau17

adding 2024 folder, removing redundant cfp page and updating organizers

2024-08-19 18:07 UTC, NorthStar commented on neurips2024/index.md
Please `git rm index.md` before committing again.

2024-08-19 18:07 UTC, NorthStar commented on neurips2024/schedule.md
Please `git rm schedule.md` before committing again.

2024-08-19 18:10 UTC, NorthStar requested changes
Hi patrick, thanks for the PR. Please remove the neurips2024 folder, which seems redundant. We keep the most updated ("current") year's programme in the uppper-level directory (i.e. just `index.md` and just `call_for_papers.md`). So please make the CFP changes there.

2024-08-20 12:18 UTC, pmusau17 commented
Thanks Mimee.  Done.

2024-08-20 12:20 UTC, pmusau17 commented
Re-opening.

2024-08-21 00:27 UTC, NorthStar approved these changes

2024-08-21 00:27 UTC, merged